### ISSUE TITLE
I would really prefer it if you reached out to me first. 

### ISSUE THREAD

**Issue by Pawlicker** [sgrigson/oliphant#2]
Hi, I'm the ceo of one of the instances in your list (fedi.pawlicker.com). I don't mind being blocked, I'm used to it at this point and in fact I've got some wagie dollars saved up to change domains as well when I move to running a multi-user setup because of how people copy/paste blocklists. However I don't appreciate the fact that you're likely copypasting instances from some massive list without even checking what is on these lists or with zero reason. This is cemented by the fact that you've included domains that have been down such as marsey.club, neckbeard.xyz, or anime.website or completely incorrect domains such as kiwifarms.net (their fedi instance has been down for a while), nonfederating websites that run Mastodon such as truthsocial, and instances that don't even talk about "hate speech" such as the9thcircle.club or bungle.online. If you bothered to read the ToS of some of these instances or reached out to the admins, you'd get a second prospective first. I only heard about this blocklist from someone on fedi.

So if you're going to blanket ban a bunch of people, maybe actually read over your list and check what the instances are hosting first. This behavior has become a notorious problem on the fediverse to the point people have begun to ditch instances that excessively block over this. Thanks for reading this.

**Comment by sgrigson** [comment]
I just inherited this, started out getting bombarded with hate speech, and started supplying a blocklist of recommendations of other people. I posted my methodology, and tenforward was one of my sources. 

The source was from a [tenforward citation](https://tenforward.social/@guinan/108988020048418999) for harassment. I absolutely *did* copy a lot of domains from there originally. There are a few ancestral domains on there that I didn't have firsthand exposure to at the time. Some defederations are over [lax moderation, or federation with nazis](https://tenforward.social/@guinan/104410516398448298).  This was the citation for [bungle.online](https://tenforward.social/@guinan/108597334963051927) for "racism, queerphobia"

It's all here.

https://wiki.tenforward.social/doku.php?id=tenforward:suspensions

I've been on the fedi for like...2 months? Just a little over, and started my own server with a few friends. This was a defensive measure on my part.

In the future, my plan is to combine sources and be a bit more careful about my own block recommendations as well.

I will remove your instance, as well as most of the others you mentioned from my blocklist for now. You're right that I was not here when any of these things supposedly happened, and you don't deserve to be added to my own list for historical issues.

I'll try to be more careful in the future, but I freely admit the list is very subjective, and I'm just sharing it with the idea that new admins should have a reasonable, fair place to start, and weeding out less well-moderated instances.

Sorry I did not communicate with you, first. I will be updating the list shortly.

**Comment by sgrigson** [comment]
I've fundamentally restructured this system to rely on [FediBlockHole](https://github.com/eigenmagic/fediblockhole) and a series of trusted sources to create block files. Mine is only one of those sources, and each file can be individually downloaded, or a merged version of all of them can be downloaded.

I do appreciate you communicating with me about this. If there is anything else you suggest that should not be on [my list](https://github.com/sgrigson/oliphant/blob/main/blocklists/oliphant.social.csv) please let me know. Mine is just one of many sources now, but it could have some impact on the other lists.

I am hopeful that providing multiple lists for download instead of only offering my own as "the list" will be a lot less offensive to the community and provide a bit more transparency to the process.

**Comment by sgrigson** [comment]
I'm going to close this issue for now. I can appreciate it doesn't feel good to have your name show up on a list without knowing why, but I've removed your instance from my own list and have pruned a few more since that are based on old, inherited information.
