### ISSUE TITLE
GDPR infringment

### ISSUE THREAD

**Issue by aeris** [sgrigson/oliphant#9]
Hello,

I'm contacting you here because your blocklist contains self-hosted mono-user personal instance domain and because i'm a European citizen and [my own domain is on this list](https://github.com/sgrigson/oliphant/blob/main/blocklists/_unified_max_blocklist.csv#L678), per se, such a list is covered by the GDPR because such a domain is a PII (personal identifiable information).

From now, this list infringes the GDPR by many means :
- scrapping of public source (article 6)
- no compatible legal basis with the original source (article 6)
- no compatible purpose with the original source (article 6)
- false or missleading information (article 6 & 16)
- no information of the subject (article 14)
- no right to oppose (article 21)
- no right to object (article 17)

Given all those violations, you have 1 month to proceed with removal of all my PII from this repository based on article 15 (access request), 16 (right to rectify false information), 17(c) (right to object), 17(d) (unlawfull processing) & 21 (right to oppose) of the GDPR. Without any action in this timeframe, I will open a case on my national data protection authority (CNIL).

NB: For your information, and you will note the dramatically irony of this situation, but currently my Mastodon bio is not terrorism support but just a joke about the fact my own government start classify everybody as terrorist without any documented or factual criteria and was then sentenced by our constitutional concil to drop this bill
https://www.nextinpact.com/article/25371/103093-le-delit-dentreprise-individuelle-terroriste-devant-conseil-constitutionnel
Any resemblance to existing characters or situations is purely coincidental… :wink:

**Comment by tiliarou** [comment]
Your bot identifying blocable domains is not working at all, not to mention the multiple infringements to privacy and associated laws in multiple jurisdiction. Also, posting plain text blocklist on github is poor practice, dangerous, and harming individuals whose domains are listed.

You still have a chance to avoid lawsuit...

**Comment by Seirdy** [comment]
For any curious fedi admins reading this issue, the domain in question is `imirhil.fr`.

Please share this domain with other instances so they can ~~add it to~~ remove it from their blocklists.

**Comment by tyrosinase** [comment]
I will happily remove it from mine, aeris, just please identify the Natural Person in question.

**Comment by aeris** [comment]
It's identif**iable** and not identif**ied**. And my state identity can be easily find.

**Comment by sgrigson** [comment]
Is this supposed to be a DSAR?

I am sorry, I'm not certain the person making the Article 15 request here (if making such a request on Github is even considered legally binding) is the person who claims I hold personal information about them.

A github account can be owned by anyone, as can a domain name. 

Proof of identity could be difficult. Normally in such a situation, if I had the personal email address of someone stored on my server, I'd ask them to log into their account to verify their ownership of the data. Since I don't hold any such data, I am not certain how to verify proof of identity from a github account.

Even if the domain name in question had WHOIS information traceable to a specific person (and it doesn't, it's anonymous) ownership of a domain does not mean that the user of a single-user instance on one of the subdomains of that top-level domain is the same person. It would be fallacious to assume so, since the person who registers a domain might do it on behalf of a friend, family member, or colleague.

In any case, isn't a request for information supposed to come first, then I request you verify your identity somehow and ownership to the information in question, and then I get a chance to respond, and *then* you get to demand I remove the information, threaten legal action, act like a little jerk tyrant, then?

I think you have this a little backward.

**Comment by aeris** [comment]
All is proofed here : https://keybase.io/aeris

**Comment by sgrigson** [comment]
I just see a page with a lot of links on it. I'm not sure how that proves anything.

**Comment by aeris** [comment]
It's cryptographic proof with every proof verifiable.

**Comment by aeris** [comment]
Proof for Github is [here](https://gist.github.com/aeris/9938739)
Domain is [here](https://imirhil.fr/.well-known/keybase.txt)

**Comment by tyrosinase** [comment]
Okay, so please explain how you're going to prevent your so-called "identifiable" domain name from appearing on my server *as a normal part of federation*?

**Comment by aeris** [comment]
GDPR is per purpose. Normal federation is another purpose so another legal basis. And no trouble with that. Only trouble with blocklist sharing.

**Comment by tyrosinase** [comment]
You should probably keep reading that GDPR thing, I bet you'll discover it has some things to say about whether it affects things that aren't businesses.

**Comment by aeris** [comment]
There is no business condition. Individual or NGO was fined too.

**Comment by tyrosinase** [comment]
For listing a domain name? I don't believe you.

**Comment by aeris** [comment]
On this topic I will be the first for private individual, but there is many cases with blocklist and other "sentence" considered as unlawfull.
I already fined an association for mailing without BCC, and you will find other private individuals fined to 10.000€ [here](https://www.enforcementtracker.com/)
![image](https://user-images.githubusercontent.com/51246/213819552-01dcc875-ee4d-408e-8242-511589b7fc12.png)
Currently 103 fines on private individual.

**Comment by aeris** [comment]
As soon as you process PII, you must comply with **all** the GDPR. Whatever the purpose or context. There is no exception at all (except one for private purpose, which is stated by CJEU as not compatible by design with social network or publication purpose).

**Comment by aeris** [comment]
If you want some cases about public blacklist trouble:
- association publishing list of doctors suspected of medical error [here](https://gdprhub.eu/index.php?title=Rb._Midden-Nederland_-_C/16/481957/KG_ZA_19-357): unlawfull, forced to remove data and from search engine
- government publishing list of people fined for canabis owning [here](https://gdprhub.eu/index.php?title=Rb._Rotterdam_-_C/10/585969_/_KG_ZA_19-1184) : unlawfull, forced to remove data
- employer using blacklist for employee screening [here] : unlawfull, fined 40.000€, forced to stop processing

**Comment by tyrosinase** [comment]
💤

None of those are comparable.

**Comment by aeris** [comment]
There are. Same trouble, blacklist are not lawfull without balancing right of people in the blacklist. It's the same trouble in the 3.

**Comment by aeris** [comment]
And typically the first is very very similar to your case.
An association acting for public interest, publishing publicly a blacklist, without real control of reason of blacklisting nor data qualification, and without balancing right of people inside. Unlawfull, illegal, and forbiden.

**Comment by tyrosinase** [comment]
I'm not seeing any similarity.

**Comment by aeris** [comment]
So just do nothing, and see you in court.
My current GDPR infringment list on my national data protection authority : https://twitter.com/aeris22/status/1604148288151642112
Will be very pleased to add one more row on it.

**Comment by flop25** [comment]
Sounds like someone here has read more the RGPD than the other...
And imagine you are saying that because you are thinking it doe apply to commercial purpose only, while there are plenty examples proving you were wrong
Imagine you are not honest and still don't admit you were wrong.

**Comment by aeris** [comment]
And take into account that managing social network or related stuff is **not** neutral from a legal point of view.
LCEN in France, ePrivacy, GDPR, DSA, DMA and 2000/31/CE in Europe, DMCA in US, just apply to you.
And currently Mastodon just completly fails and sucks at this point, every admin expect to be able to do everything freely but this is a topic **highly** covered by differents laws.

**Comment by tyrosinase** [comment]
🥱 I'll take you seriously when you mail me something I can actually show to my lawyer. DMCA address on my instance will work for this too.

So what's your stance on sovereign citizenship? I feel like that would be right up your alley.

**Comment by tiliarou** [comment]
It's amazing how some people just like to waste their time and the one of others by being fucking moron and making sure they really pretend to not understand...
Unbelievable.
You flagged something wrongly, just admit it, fix your mistake and move on.

**Comment by tiliarou** [comment]
> 🥱 I'll take you seriously when you mail me something I can actually show to my lawyer. DMCA address on my instance will work for this too.
> 
> So what's your stance on sovereign citizenship? I feel like that would be right up your alley.

Fuck DMCA. This has nothing to do with it. This is just plain basic privacy right under GDPR.
"sovereign citizenship" 😂 ça you be more off topic?

**Comment by Seirdy** [comment]
> It's amazing how some people just like to waste their time and the one of others by being fucking moron and making sure they really pretend to not understand...
> Unbelievable.
> You flagged something wrongly, just admit it, fix your mistake and move on.

I'm sorry, was this addressed to the owner of `imirhil.fr` or someone else?

**Comment by Exagone313** [comment]
Your instance says:

> Oliphant skews far to the left, many members are actively anti-fascist, anti-racist, and accept no trolling or harassment--and rarely federate with any servers who do. (If we do so, it's probably an accident or oversight.)

But adding single-user instances to your blocklists might be considered targeted harassment.

**Comment by aeris** [comment]
> But adding single-user instances to your blocklists might be considered targeted harassment.

It's even more. Currently blocking such instance must be address as an **account** and not an **instance**.
Admins just divert possibility to block the account at instance level. If I was on `mastodon.social` for example, I won't be ban (spoiler : I have account on this instance too).

**Comment by aeris** [comment]
> yawning_face I'll take you seriously when you mail me something I can actually show to my lawyer. DMCA address on my instance will work for this too.

You have. The first post is a legal request.

**Comment by tyrosinase** [comment]
Maybe for Oliphant. Not me.

**Comment by r3g-5z** [comment]
@aeris A random GitHub issue is not a "legal request". If you really think your baseless threats truly have any kind of value to them, consider contacting GitHub support and/or file a DMCA claim. 

Your "my personal domain is on a random list and violates GDPR" makes zero sense. Does that mean malware IOC lists of domains, IP addresses, hashes, etc violate GDPR because they're "scrapping of public source (article 6)" (your words)? You gonna sue those people too? How about those C2 malware bots that post when an HTTP endpoint hosting malware? Violates GDPR too? Hope you're ready to take down the entire cybersecurity industry then if you think this is a "GDPR violation".

Seems like you're using [FBA here](https://social.imirhil.fr/@aeris/109720883485185382). You complain about "scrapping of public source (article 6)", but the tool made by kiwifarmers you're using is literally doing that. By your own words, isn't that also a GDPR violation? You gonna take that down with your baseless legal threats too? Or are you going to eat your own words and just continue to have your followers brigade this issue.

**Comment by aeris** [comment]
> @aeris A random GitHub issue is not a "legal request". If you really think your baseless threats truly have any kind of value to them, consider contacting GitHub support and/or file a DMCA claim.

Github doesn't give a shit but yeah, without action it will be a DMCA claim and all this repo will be wiped.

> Your "my personal domain is on a random list and violates GDPR" makes zero sense. Does that mean malware IOC lists of domains, IP addresses, hashes, etc violate GDPR because they're "scrapping of public source (article 6)" (your words)?

No, because this is not PII in such a case, it's probability 0 for a malware or IOC to be operated under personal domain or IP, just… because people doing malware try as most as possible to NOT being identifiable.
The GDPR only apply for PII, so no PII, no GDPR.

> You gonna take that down with your baseless legal threats too? Or are you going to eat your own words and just continue to have your followers brigade this issue.

In this case, there is a little difference. The source PII is the **blocking** domain for single user instance and not the **blocked** domain. Blocked domain is also a little in trouble from GDPR point of view here, but from collateral damage.
And so, I will be happy to take legal action too (and against kiwifarmers, double interest)… if I can. Legally I can't because at this time, my own domain is NOT scrapped or stored directly, so I have legally no interested in actying and only a single-user **SCRAPPED** instance can take legal action. Any takedown action from me may be refused by an DPA.

**Comment by tyrosinase** [comment]
Wow, just openly admitting you're going to file a bogus DMCA claim? Bold choice.

**Comment by Absolucy** [comment]
Would you have happened to have ever heard of the Streisand Effect?

**Comment by sgrigson** [comment]
@aeris 
[Please use this form to file a DSAR request](https://forms.gle/WZEwU8E6oB8RhQEN8)

I am closing this issue.
